//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasaDePedro
{
    using System;
    using System.Collections.Generic;
    
    public partial class facilitypicgallery
    {
        public int Id { get; set; }
        public string PicUrl { get; set; }
        public string Description { get; set; }
        public Nullable<sbyte> FacilityUnitId { get; set; }
        public string EditedBy { get; set; }
    
        public virtual facilityunit facilityunit { get; set; }
    }
}
