//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasaDePedro
{
    using System;
    using System.Collections.Generic;
    
    public partial class hotelcoresubservice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hotelcoresubservice()
        {
            this.facilityunits = new HashSet<facilityunit>();
        }
    
        public sbyte Id { get; set; }
        public string SubService { get; set; }
        public Nullable<sbyte> CoreServiceId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<facilityunit> facilityunits { get; set; }
        public virtual hotelcoreservice hotelcoreservice { get; set; }
    }
}
