//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasaDePedro
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbo_casadepedroEntities : DbContext
    {
        public dbo_casadepedroEntities()
            : base("name=dbo_casadepedroEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<hotel> hotels { get; set; }
        public virtual DbSet<meetingeventreservation> meetingeventreservations { get; set; }
        public virtual DbSet<meetingeventvenue> meetingeventvenues { get; set; }
        public virtual DbSet<restaurantbarreservation> restaurantbarreservations { get; set; }
        public virtual DbSet<restaurantbarvenue> restaurantbarvenues { get; set; }
        public virtual DbSet<roomreservation> roomreservations { get; set; }
        public virtual DbSet<roomtype> roomtypes { get; set; }
        public virtual DbSet<facilitypicgallery> facilitypicgalleries { get; set; }
        public virtual DbSet<facilityunit> facilityunits { get; set; }
        public virtual DbSet<hotelcoreservice> hotelcoreservices { get; set; }
        public virtual DbSet<hotelcoresubservice> hotelcoresubservices { get; set; }
        public virtual DbSet<homepageslider> homepagesliders { get; set; }
        public virtual DbSet<pagecontent> pagecontents { get; set; }
    }
}
