//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasaDePedro
{
    using System;
    using System.Collections.Generic;
    
    public partial class roomreservation
    {
        public int id { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<sbyte> NoOfAdult { get; set; }
        public Nullable<sbyte> NoOfChild { get; set; }
        public Nullable<sbyte> HotelId { get; set; }
        public Nullable<sbyte> RoomTypeId { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Comment { get; set; }
        public Nullable<bool> BookingConfirmed { get; set; }
        public string ConfirmedBy { get; set; }
    
        public virtual hotel hotel { get; set; }
        public virtual roomtype roomtype { get; set; }
    }
}
